apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2  # Number of replicas (pods) of your application
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: localhost:5000/app:latest  # Replace with your image name
        ports:
        - containerPort: 8080  # Replace with your application port