apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80  # External port for accessing your application (can be different from container port)
      targetPort: 8080  # Port your application listens on within the container
  type: LoadBalancer  # Choose a service type based on your needs (e.g., LoadBalancer for external access)